package game

SCREEN_WIDTH  :: 640
SCREEN_HEIGHT :: 360
TILE_SIZE     :: 16
TARGET_FPS    :: 60

PLAYER_SPEED   :: 130.0
GRAVITY        :: 500.0
JUMP_VELOCITY  :: -230.0
MAX_FALL_SPEED :: 400.0
MAX_JUMPS      :: 2

PLAYER_HITBOX_W :: 8
PLAYER_HITBOX_H :: 14

SPRITE_SRC_SIZE :: 16
SPRITE_DST_SIZE :: 16

SPEAR_SPRITE_SIZE :: 32
SPEAR_ONESHOT_FPS :: 12.0

// Animation Speeds
ANIM_FRAME_TIME :: 0.14 //Baseline
ANIM_PLAYER_IDLE_TIME :: ANIM_FRAME_TIME + 0.5
ANIM_SPEAR_IDLE_TIME :: ANIM_FRAME_TIME + 0.5
ANIM_SPEAR_SPAWN_TIME :: ANIM_FRAME_TIME + 0.3
ANIM_PLAYER_THROWS_SPEAR_TIME :: ANIM_FRAME_TIME -.02 // The actual player sprite animation, not the spear sprite
ANIM_PLAYER_TELEPORT_TIME :: 0.28

CAMERA_ZOOM :: f32(2.0)
CAMERA_FOLLOW_SPEED :: 7.5

PLAYER_MAX_HP :: 70
PLAYER_FOOTSTEP_INTERVAL :: 0.26

// Enemy
ENEMY_CHERUB_HP            :: 40
ENEMY_CHERUB_SPEED         :: 60.0
ENEMY_CHERUB_HITBOX_W      :: 10
ENEMY_CHERUB_HITBOX_H      :: 12
ENEMY_CHERUB_PATROL_DIST   :: 48.0
ENEMY_CHERUB_ATTACK_RANGE  :: 240.0
ENEMY_CHERUB_ATTACK_TIME   :: 0.36 // 3 frames at ANIM_FRAME_TIME
ENEMY_CHERUB_ATTACK_COOLDOWN :: 2.5
MAX_ENEMIES                :: 32
MAX_DECORATIVE_SIGNS      :: 16
MAX_COMBAT_TARGETS        :: MAX_ENEMIES + MAX_DECORATIVE_SIGNS
MAX_WAVE_ENEMY_TYPES      :: 8
WAVE_SPAWN_ATTEMPTS       :: 32
ENEMY_HP_BAR_W            :: 14
ENEMY_HP_BAR_H            :: 2
ENEMY_HP_BAR_Y_OFFSET     :: 4

// Enemy — Ghoul
ENEMY_GHOUL_HP            :: 50
ENEMY_GHOUL_SPEED         :: 40.0
ENEMY_GHOUL_HITBOX_W      :: 10
ENEMY_GHOUL_HITBOX_H      :: 14
ENEMY_GHOUL_PATROL_DIST   :: 32.0
ENEMY_GHOUL_CHARGE_SPEED  :: 120.0
ENEMY_GHOUL_MELEE_RANGE   :: 32.0
ENEMY_GHOUL_ATTACK_DAMAGE :: 19
GHOUL_FX_FRAME_SIZE       :: 32

// Enemy — Mutant Cherub
ENEMY_MUTANT_CHERUB_HP            :: 82
ENEMY_MUTANT_CHERUB_SPEED         :: 16.0
ENEMY_MUTANT_CHERUB_CHARGE_SPEED  :: 28.0
ENEMY_MUTANT_CHERUB_HITBOX_W      :: 14
ENEMY_MUTANT_CHERUB_HITBOX_H      :: 24
ENEMY_MUTANT_CHERUB_PATROL_DIST   :: 24.0
ENEMY_MUTANT_CHERUB_ATTACK_RANGE  :: 64.0
ENEMY_MUTANT_CHERUB_ATTACK_DAMAGE :: 26
MUTANT_CHERUB_SPRITE_SIZE         :: 32

// Psychic projectile
PSYCHIC_DAMAGE          :: 8
PSYCHIC_SPEED           :: 160.0
PSYCHIC_ARC_GRAVITY     :: 180.0
PSYCHIC_MIN_TRAVEL_TIME :: 0.2
PSYCHIC_LIFETIME        :: 3.0
MAX_PSYCHIC_PROJECTILES :: 32

// Combat
SPEAR_THROW_DAMAGE      :: 14
COMBAT_RANGE            :: 200.0
SPEAR_PROJECTILE_SPEED  :: 350.0
SPEAR_RETURN_SPEED      :: 400.0
SPEAR_HIT_RADIUS        :: 6.0
SPEAR_HIT_PAUSE_TIME    :: 0.16
SPEAR_TELEPORT_STRIKE_DAMAGE :: 42
SPEAR_TELEPORT_STRIKE_KNOCKBACK_X :: 180.0
SPEAR_TELEPORT_STRIKE_KNOCKBACK_Y :: -90.0
ENEMY_KNOCKBACK_FRICTION :: 900.0
TELEPORT_SEARCH_RADIUS  :: 48
TELEPORT_SEARCH_STEP    :: 4
TELEPORT_BELOW_PENALTY  :: 1024.0

PLAYER_HIT_FLASH_DURATION :: 0.3

HP_BAR_X       :: 8
HP_BAR_Y       :: SCREEN_HEIGHT - HP_BAR_H - 8
HP_BAR_W       :: 64
HP_BAR_H       :: 6
HP_BAR_OUTLINE :: 1
