package game

SCREEN_WIDTH  :: 640
SCREEN_HEIGHT :: 360
TILE_SIZE     :: 16
TARGET_FPS    :: 60

PLAYER_SPEED   :: 130.0
GRAVITY        :: 500.0
JUMP_VELOCITY  :: -230.0
MAX_FALL_SPEED :: 400.0
MAX_JUMPS      :: 2

PLAYER_HITBOX_W :: 8
PLAYER_HITBOX_H :: 14

SPRITE_SRC_SIZE :: 16
SPRITE_DST_SIZE :: 16

SPEAR_SPRITE_SIZE :: 32
SPEAR_ONESHOT_FPS :: 12.0

// Animation Speeds
ANIM_FRAME_TIME :: 0.12 //Baseline
ANIM_PLAYER_IDLE_TIME :: ANIM_FRAME_TIME + 0.5
ANIM_SPEAR_IDLE_TIME :: ANIM_FRAME_TIME + 0.5
ANIM_SPEAR_SPAWN_TIME :: ANIM_FRAME_TIME + 0.3

CAMERA_ZOOM :: f32(1.7)
