package game

SCREEN_WIDTH  :: 640
SCREEN_HEIGHT :: 360
TILE_SIZE     :: 16
TARGET_FPS    :: 60

PLAYER_SPEED   :: 130.0
GRAVITY        :: 500.0
JUMP_VELOCITY  :: -230.0
MAX_FALL_SPEED :: 400.0
MAX_JUMPS      :: 2

PLAYER_HITBOX_W :: 8
PLAYER_HITBOX_H :: 14

SPRITE_SRC_SIZE :: 16
SPRITE_DST_SIZE :: 16

SPEAR_SPRITE_SIZE :: 32
SPEAR_ONESHOT_FPS :: 12.0

// Animation Speeds
ANIM_FRAME_TIME :: 0.12 //Baseline
ANIM_PLAYER_IDLE_TIME :: ANIM_FRAME_TIME + 0.5
ANIM_SPEAR_IDLE_TIME :: ANIM_FRAME_TIME + 0.5
ANIM_SPEAR_SPAWN_TIME :: ANIM_FRAME_TIME + 0.3

CAMERA_ZOOM :: f32(1.7)

PLAYER_MAX_HP :: 70

// Enemy
ENEMY_CHERUB_HP            :: 40
ENEMY_CHERUB_SPEED         :: 60.0
ENEMY_CHERUB_HITBOX_W      :: 10
ENEMY_CHERUB_HITBOX_H      :: 12
ENEMY_CHERUB_PATROL_DIST   :: 48.0
ENEMY_CHERUB_ATTACK_RANGE  :: 240.0
ENEMY_CHERUB_ATTACK_TIME   :: 0.36 // 3 frames at ANIM_FRAME_TIME
ENEMY_CHERUB_ATTACK_COOLDOWN :: 2.5
MAX_ENEMIES                :: 16

// Enemy — Ghoul
ENEMY_GHOUL_HP            :: 50
ENEMY_GHOUL_SPEED         :: 40.0
ENEMY_GHOUL_HITBOX_W      :: 10
ENEMY_GHOUL_HITBOX_H      :: 14
ENEMY_GHOUL_PATROL_DIST   :: 32.0
ENEMY_GHOUL_CHARGE_SPEED  :: 120.0
ENEMY_GHOUL_MELEE_RANGE   :: 32.0
ENEMY_GHOUL_ATTACK_DAMAGE :: 19
GHOUL_FX_FRAME_SIZE       :: 32

// Psychic projectile
PSYCHIC_DAMAGE          :: 8
PSYCHIC_SPEED           :: 160.0
PSYCHIC_ARC_GRAVITY     :: 180.0
PSYCHIC_LIFETIME        :: 3.0
MAX_PSYCHIC_PROJECTILES :: 32

// Combat
SPEAR_THROW_DAMAGE      :: 14
COMBAT_RANGE            :: 200.0
SPEAR_PROJECTILE_SPEED  :: 350.0
SPEAR_RETURN_SPEED      :: 400.0
SPEAR_HIT_RADIUS        :: 6.0
PLAYER_THROW_HOLD_TIME  :: 0.15

PLAYER_HIT_FLASH_DURATION :: 0.3

HP_BAR_X       :: 8
HP_BAR_Y       :: SCREEN_HEIGHT - HP_BAR_H - 8
HP_BAR_W       :: 64
HP_BAR_H       :: 6
HP_BAR_OUTLINE :: 1
